### ISSUE TITLE
UniqueEntity constraint not working in unit tests

### ISSUE THREAD

**Issue by Badlapje** [howest-wsde/VrijwilligersTool#92]
Any Entity with UniqueEntity constraints currenlty needs to be unit tested with those constraints temporarily removed.  Leaving them there causes an error to be thrown and the test fails to run.

**Comment by Badlapje** [comment]
Created an issue for the symfony docs to clarify how this should be handled at https://github.com/symfony/symfony-docs/issues/6532 

So far as i can google the uniqueEntityValidator needs to be declared as a service. I tried that but it didn't work ... will pick this up after it's adjusted in docs (hopefully) or once all basic functionality has been created).

**Comment by SnelleJelle** [comment]
in services.yml it states:
```
services:
    doctrine.orm.validator.unique:
        class: Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator }
```
Is it safe to comment this snippet since it breaks the @UniqueEntity constraint in the entity validation?
